language: scala
jdk:
- oraclejdk8
scala:
- 2.11.8
env:
  global:
    secure: vufj72ZKAoRFxILfvcBBqMv/EGkJy+d65wUeNwel6LSpLFwdo8Dw31xRg87UvF035gjLRstDXwS3bdZ1pLbojA6PCJRfw1RBZpW4uJ+y1ubrD8vHe3aTQV0sDjFQbB2xjWpzJigK6vrPH/V1i0qq9hqxYkYRL2hBO+yeaiJWFJvEYoS9ccQZuMJx5t+4Ic8Y3crhVv/iUNdplmp0YReT05NHe42ak2YXnIHSyqY7grxNp77IGU6HlNL2MjJEGE5ABBo0vAfQhYqcwIKkC5zmUdNUGbjWkbmxsGEdW7JHWJH1IQYjl/7Fn3Y4xQxIatTzIIGnIkJvg3N8K2+CWA1hhpkqAjn15LhR6vFYwfejfc+Ibih6PKMZRCfCQWZuBA7i6FTUSfeTEcqsCdlZCiuDFbac7Xr6eeLAmR0wEbcx4OkDEiN65gvyqLJotGEd9cd+F4i4PHnex8D3Yxh27zyefgk8mN3hLJjzVotMKZ/77bJYrjYiR5811IxXiKeWk2D5UGHitHXPwZtw74CtSL88eFTmQDV8T8foUH3fqs/OyjkuWzwa8e+geWTV6Sqb7EZ+jZVWC86EV6fazbDgktlnolJlTxTIYpUHHNC8+LD8d4mpSZXZY94pC/pgf+4eqHGE3IqNMLK4QArVH40qWkJOANogwbGVrsfSRg6TNap2WGc=
script: sbt clean test
script: sbt clean coverage test
after_success: sbt coverageReport coveralls